export const CARD_LOADING = "CARD_LOADING";
export const CARD_LOADING_SUCCESS = "CARD_LOADING_SUCCESS";
export const CARD_LOADING_ERROR = "CARD_LOADING_ERROR";

export const SEARCH_CARD = "SEARCH_CARD";
export const SEARCH_CARD_SUCCESS = "SEARCH_CARD_SUCCESS";
export const SEARCH_CARD_ERROR = "SEARCH_CARD_ERROR";